[tool.poetry]
name = "jyyslide-md"
version = "0.1.0"
description = ""
authors = ["zweix123 <1979803044@qq.com>"]
readme = "README.md"
packages = [{include = "jyyslide_md"}]

[tool.poetry.dependencies]
python = "^3.11"
pyquery = "^2.0.0"
jinja2 = "^3.1.2"
chardet = "^5.1.0"
aiohttp = "^3.8.4"
tqdm = "^4.65.0"
requests = "^2.28.2"
markdown = "^3.4.1"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
